# Toml Configuration File 

[server]
ServerAddress = "0.0.0.0:8080"
ServerRetries = 3
ServerRetryTimeout = 20


[MySQL]
Host = "alpha"
Username = "sgrzywocz"
Password = "123test"
Database = "db"
Timezone = "UTC" 

[logging]
ApiLogPath = "log/error.log"
LogLevel = "all"

